### Sorting Arrays 


In [2]:
import numpy as np
r1 = np.random.randint(10, size=(3,5))
r1

array([[7, 1, 5, 5, 8],
       [4, 1, 1, 7, 3],
       [7, 5, 9, 9, 7]])

In [3]:
np.sort(r1)


array([[1, 5, 5, 7, 8],
       [1, 1, 3, 4, 7],
       [5, 7, 7, 9, 9]])

In [4]:
np.argmax(r1, axis=0)

array([0, 2, 2, 2, 0], dtype=int64)

In [6]:
np.argmax(r1, axis=1)

array([4, 3, 2], dtype=int64)

### Numpy with Pandas

In [7]:
r2 = r1.T
r2

array([[7, 4, 7],
       [1, 1, 5],
       [5, 1, 9],
       [5, 7, 9],
       [8, 3, 7]])

In [11]:
#Create weekly sales dataframe
import pandas as pd
weekly_sales = pd.DataFrame(r2,
                           index=["Mon", "Tues", "Wed", "Thurs","Fri"],
                           columns=["Almonds", "Peanuts","Cashew"])
weekly_sales

Almonds  Peanuts  Cashew
Mon          7        4       7
Tues         1        1       5
Wed          5        1       9
Thurs        5        7       9
Fri          8        3       7

In [19]:
#create prices array
p1 = np.array([10,8,12])
p1

array([10,  8, 12])

In [20]:
#create prices as dataframe
df = pd.DataFrame(p1.reshape(1,3),index=["Price"],columns=["Almond","Peanuts", "Cashew"])
df

Almond  Peanuts  Cashew
Price      10        8      12

In [31]:
p3 = p1.reshape(1,3)
r3 = r2.T
weekly_sales.shape, df.shape

((5, 3), (1, 3))

In [30]:
total_sales = p3.dot(r3)

In [27]:
total_sales


array([[186,  78, 166, 214, 188]])

In [34]:
weekly_sales["Totals ($)"] = total_sales.T
weekly_sales

Almonds  Peanuts  Cashew  Totals ($)
Mon          7        4       7         186
Tues         1        1       5          78
Wed          5        1       9         166
Thurs        5        7       9         214
Fri          8        3       7         188

### Turn images into Numpy Arrays

In [45]:
%%html
<img src="images/panda.png"/>

In [49]:
#Turn image into Numpy Array
from matplotlib.image import imread

panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [50]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [58]:
panda[:2]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)